spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    zuul-sale-service:
      path: /sale/**
    routerTest:
      path: /routeTest/163/**
      url: http://www.163.com