server:
  port: 9000
spring:
  application:
    name: service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    HelloClient#hello():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics